// SPDX-FileCopyrightText: murmurhash3_crossval.rs 2026, ["François Cami" <contribs@fcami.net>]
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Cross-validation of our murmurhash3 against SSSD's C implementation.
//!
//! Reads reference hashes from tests/fixtures/<version>/hashes.txt
//! (generated by the C gen_cache tool using SSSD's murmurhash3).

use std::path::PathBuf;

use sssd_mc::murmurhash3::murmurhash3;

fn fixtures_dir(version: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(version)
}

/// Parse a hex string into bytes.
fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex"))
        .collect()
}

/// Parse hashes.txt and verify each entry against our implementation.
fn verify_hashes(version: &str) {
    let path = fixtures_dir(version).join("hashes.txt");
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read {}: {e}. Run `just gen-fixtures {version}` first.",
            path.display()
        )
    });

    let mut count = 0;
    for line in content.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }

        let parts: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(parts.len(), 3, "Bad line in hashes.txt: {line}");

        let key_hex = parts[0];
        let seed = u32::from_str_radix(parts[1], 16).expect("valid seed hex");
        let expected = u32::from_str_radix(parts[2], 16).expect("valid hash hex");

        let key = if key_hex == "(empty)" {
            vec![]
        } else {
            hex_to_bytes(key_hex)
        };

        let actual = murmurhash3(&key, seed);
        assert_eq!(
            actual, expected,
            "murmurhash3 mismatch for key={key_hex} seed={seed:#010x}: got {actual:#010x}, expected {expected:#010x}"
        );
        count += 1;
    }

    assert!(count > 0, "No hash entries found in {}", path.display());
    eprintln!("  Verified {count} murmurhash3 values against SSSD {version}");
}

#[test]
fn crossval_head() {
    verify_hashes("head");
}
